# Concerns


Communication issues

While some campuses presented a unified front across coordinating units, others were not as unified.

A reluctance to help students
Dismissive of concerns

Students have limited knowledge of insurance requirements, and of insurance in general.

A sense of 'its someone elses responsibility'

Poor communication leading to disastisfied students

Communication misalignment

Miscommunication - to communicate unclearly or inadequately.
Communication misalignment - communication from one party isn't addressing the concerns of the other

Known issues about insurance not being communicated to the students


Safety culture issues

Varying levels of engagement by faculty. Some were very active, others very hands-off. Very few expressed knowledge of insurance or liability issues.


issues of students
Students have limited experience
Leadership changes nearly every year
Knowledge transfer year after year is inconsistent
Lack of points of support, especially for siloed departments
Complex interweaving of issues - space allocation, safety, insurance, rso responsibilities, etc
Students need to be taught

Transparency issues
